"""Add is_read to Book model

Revision ID: 49b8f612cc3e
Revises: 4f5c02bd44c0
Create Date: 2025-08-14 20:45:17.413045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49b8f612cc3e'
down_revision = '4f5c02bd44c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('is_read', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'is_read')
    # ### end Alembic commands ###
