"""Add description and rating to Book model

Revision ID: 4f5c02bd44c0
Revises: 1a2b3c4d5e6f
Create Date: 2025-08-14 20:27:38.717201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f5c02bd44c0'
down_revision = '1a2b3c4d5e6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('description', sa.String(), nullable=True))
    op.add_column('books', sa.Column('rating', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'rating')
    op.drop_column('books', 'description')
    # ### end Alembic commands ###
